[package]
name = "vital-script-runner"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
vital-script-ops.workspace = true
vital-script-primitives.workspace = true
vital-script-instruction.workspace = true

[features]
default = ["std"]
std = [
    "vital-script-ops/std",
    "vital-script-instruction/std",
    "vital-script-primitives/std",
]
