[package]
name = "vital-script-primitives"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
log = { workspaces = true, optional = true }

[dev-dependencies]
log.workspace = true
env_logger.workspace = true

[features]
default = ["std"]
std = []
log = [
    "dep:log"
]