[package]
name = "vital-script-primitives"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
primitive-types = { workspace = true }

[features]
default = ["std"]
std = [
    "bytes/std",
    "primitive-types/std",
]
